import type {SettingsPageDefinition,SettingsPageRegistration} from '@agora-de/domain';
import type {ShortcutAssignment,ShortcutDefinition} from '@agora-de/protocol';

export function shortcutConflicts(assignments:readonly ShortcutAssignment[]):ReadonlyMap<string,string>{const owners=new Map<string,string>(),conflicts=new Map<string,string>();for(const item of assignments){const key=item.accelerator.trim().replace(/\s+/g,' ').toUpperCase();const owner=owners.get(key);if(owner){conflicts.set(item.id,owner);conflicts.set(owner,item.id)}else owners.set(key,item.id)}return conflicts;}
export function filterShortcutDefinitions(definitions:readonly ShortcutDefinition[],query:string):readonly ShortcutDefinition[]{const value=query.trim().toLowerCase();return value?definitions.filter((item)=>`${item.title} ${item.group} ${item.id}`.toLowerCase().includes(value)):definitions;}

export const shortcutsSettingsPage:SettingsPageDefinition={moduleId:'shortcuts',uiEntryPoint:'settings-shortcuts',title:'Shortcuts',renderPanel:()=>`<style>
  .shortcut-toolbar{display:flex;gap:10px}.shortcut-toolbar input{background:var(--agora-bg);border:2px solid var(--agora-border);color:var(--agora-fg);min-height:42px;padding:7px 10px;width:min(420px,100%)}.shortcut-groups{display:grid;gap:18px}.shortcut-group{display:grid;gap:8px}.shortcut-row{align-items:center;background:var(--agora-surface);border:1px solid var(--agora-border-subtle);display:grid;gap:10px;grid-template-columns:minmax(160px,1fr) minmax(220px,1fr) auto auto;padding:12px}.shortcut-row input{background:var(--agora-bg);border:2px solid var(--agora-border);color:var(--agora-fg);min-height:42px;padding:7px 9px}.shortcut-row.conflict{border-color:var(--agora-warning)}.shortcut-default{color:var(--agora-text-muted);font-size:12px}.shortcut-error{color:var(--agora-warning);grid-column:1/-1}.shortcut-reserved{font-size:12px}
  @media(max-width:760px){.shortcut-row{grid-template-columns:1fr}.shortcut-error{grid-column:auto}}
  </style><section class="settings-module-panel" data-settings-module="shortcuts"><label class="shortcut-toolbar">Search shortcuts<input id="shortcut-search" type="search" autocomplete="off"></label><p id="shortcut-status" role="status" aria-live="polite">Loading managed bindings…</p><div class="shortcut-groups" id="shortcut-groups"></div></section>`,renderClientController:()=>String.raw`(api)=>{
  const search=api.content.querySelector("#shortcut-search"),groups=api.content.querySelector("#shortcut-groups"),status=api.content.querySelector("#shortcut-status");let recording="";
  function assignment(id){return api.getDraft().assignments.find((item)=>item.id===id);}function defaultFor(id){return api.getModuleState().defaults.assignments.find((item)=>item.id===id)?.accelerator||"";}
  function normalized(value){return value.trim().replace(/\s+/g," ").toUpperCase();}function conflictMap(){const owners=new Map(),result=new Map();api.getDraft().assignments.forEach((item)=>{const key=normalized(item.accelerator),owner=owners.get(key);if(owner){result.set(item.id,owner);result.set(owner,item.id)}else owners.set(key,item.id);});return result;}
  function accelerator(event){const mods=[];if(event.metaKey)mods.push("<super>");if(event.ctrlKey)mods.push("<ctrl>");if(event.altKey)mods.push("<alt>");if(event.shiftKey)mods.push("<shift>");if(!mods.length||["Meta","Control","Alt","Shift"].includes(event.key))return "";const key=event.code.startsWith("Key")?"KEY_"+event.code.slice(3):event.code.startsWith("Digit")?"KEY_"+event.code.slice(5):"KEY_"+event.key.toUpperCase().replace(/[^A-Z0-9]+/g,"_");return mods.join(" ")+" "+key;}
  function render(){const state=api.getModuleState(),draft=api.getDraft();if(!state||!draft)return;const query=search.value.trim().toLowerCase(),conflicts=conflictMap(),byGroup=new Map();state.definitions.filter((item)=>!query||(item.title+" "+item.group+" "+item.id).toLowerCase().includes(query)).forEach((item)=>{if(!byGroup.has(item.group))byGroup.set(item.group,[]);byGroup.get(item.group).push(item);});groups.replaceChildren();byGroup.forEach((items,name)=>{const section=document.createElement("section");section.className="shortcut-group";const heading=document.createElement("h3");heading.textContent=name;section.appendChild(heading);items.forEach((definition)=>{const current=assignment(definition.id),row=document.createElement("div");row.className="shortcut-row"+(conflicts.has(definition.id)?" conflict":"");row.id="shortcut-"+definition.id;const label=document.createElement("label");label.htmlFor="shortcut-input-"+definition.id;const title=document.createElement("strong");title.textContent=definition.title;const detail=document.createElement("span");detail.className="shortcut-default";detail.textContent="Default: "+defaultFor(definition.id);label.append(title,document.createElement("br"),detail);const input=document.createElement("input");input.id="shortcut-input-"+definition.id;input.value=current.accelerator;input.disabled=definition.reserved;input.setAttribute("aria-label",definition.title+" accelerator");input.addEventListener("change",()=>{current.accelerator=input.value;api.markDirty();render();});const record=document.createElement("button");record.type="button";record.textContent=recording===definition.id?"Press shortcut…":"Record";record.disabled=definition.reserved;record.addEventListener("click",()=>{recording=definition.id;status.textContent="Recording "+definition.title+". Press a modified key, or Escape to cancel.";render();api.content.focus();});const reset=document.createElement("button");reset.type="button";reset.textContent="Reset";reset.disabled=definition.reserved;reset.addEventListener("click",()=>{current.accelerator=defaultFor(definition.id);api.markDirty();render();});row.append(label,input,record,reset);if(definition.reserved){const note=document.createElement("span");note.className="shortcut-error shortcut-reserved";note.textContent="Reserved so Settings always remains reachable.";row.appendChild(note)}else if(conflicts.has(definition.id)){const error=document.createElement("a");error.className="shortcut-error";error.href="#shortcut-"+conflicts.get(definition.id);error.textContent="Conflicts with "+conflicts.get(definition.id);row.appendChild(error)}section.appendChild(row)});groups.appendChild(section)});status.textContent=conflicts.size?conflicts.size+" conflicting bindings must be resolved.":recording?status.textContent:"Managed shortcuts ready.";}
  search.addEventListener("input",render);api.content.tabIndex=-1;api.content.addEventListener("keydown",(event)=>{if(!recording)return;if(event.key==="Escape"){recording="";status.textContent="Recording cancelled.";render();return}const value=accelerator(event);if(!value){status.textContent="Use at least one modifier plus a non-modifier key.";return}event.preventDefault();assignment(recording).accelerator=value;recording="";api.markDirty();render();});return {render};
}`,};
export const shortcutsSettingsPageRegistration:SettingsPageRegistration={uiEntryPoint:shortcutsSettingsPage.uiEntryPoint,load:async()=>shortcutsSettingsPage};
export function assertShortcutFixtures():void{const assignments=[{id:'a',accelerator:'<super> KEY_J'},{id:'b',accelerator:' <SUPER>  KEY_J '}];if(shortcutConflicts(assignments).size!==2)throw new Error('normalized conflicts must identify both rows');if(filterShortcutDefinitions([{id:'settings',title:'Open Settings',group:'Navigation',reserved:true}],'open').length!==1)throw new Error('shortcut search failed');const source=shortcutsSettingsPage.renderClientController?.()??'';for(const marker of ['event.metaKey','modifier plus a non-modifier','definition.reserved','Default: ','conflict'])if(!source.includes(marker))throw new Error(`shortcut controller missing ${marker}`);}
