// Code generated by protocol-codegen. DO NOT EDIT.
// Source of truth: de-rs/crates/protocol/protocol-settings.

package settingsprotocol

import (
	"bytes"
	"encoding/json"
	"errors"
)

const (
	SettingsSchemaVersion      uint16 = 1
	DiagnosticsContractVersion uint16 = 1
	DiagnosticsModuleID               = "diagnostics"
	DisplaysContractVersion    uint16 = 1
	DisplaysModuleID                  = "displays"
	WindowManagementContractVersion uint16 = 1
	WindowManagementModuleID                = "window-management"
	AppearanceContractVersion       uint16 = 1
	AppearanceModuleID                     = "appearance"
	ShortcutsContractVersion        uint16 = 1
	ShortcutsModuleID                      = "shortcuts"
)

type SettingsCategory string

const (
	SettingsCategoryHardware SettingsCategory = "hardware"
	SettingsCategoryPersonal SettingsCategory = "personal"
	SettingsCategorySystem   SettingsCategory = "system"
)

type SettingsCapability string

const (
	SettingsCapabilityLoad            SettingsCapability = "load"
	SettingsCapabilityValidate        SettingsCapability = "validate"
	SettingsCapabilityApply           SettingsCapability = "apply"
	SettingsCapabilityRestoreDefaults SettingsCapability = "restore_defaults"
)

type SettingsAvailabilityState string

const (
	SettingsAvailabilityAvailable   SettingsAvailabilityState = "available"
	SettingsAvailabilityReadOnly    SettingsAvailabilityState = "read_only"
	SettingsAvailabilityUnavailable SettingsAvailabilityState = "unavailable"
	SettingsAvailabilityUnsupported SettingsAvailabilityState = "unsupported"
)

type SettingsOperation string

const (
	SettingsOperationLoad            SettingsOperation = "load"
	SettingsOperationValidate        SettingsOperation = "validate"
	SettingsOperationApply           SettingsOperation = "apply"
	SettingsOperationReset           SettingsOperation = "reset"
	SettingsOperationRestoreDefaults SettingsOperation = "restore_defaults"
	SettingsOperationKeep            SettingsOperation = "keep"
	SettingsOperationRevert          SettingsOperation = "revert"
)

type SettingsErrorCode string

const (
	SettingsErrorInvalidRequest      SettingsErrorCode = "invalid_request"
	SettingsErrorValidation          SettingsErrorCode = "validation_failed"
	SettingsErrorStaleRevision       SettingsErrorCode = "stale_revision"
	SettingsErrorUnsupported         SettingsErrorCode = "unsupported"
	SettingsErrorUnavailable         SettingsErrorCode = "unavailable"
	SettingsErrorTimeout             SettingsErrorCode = "timeout"
	SettingsErrorApplyFailed         SettingsErrorCode = "apply_failed"
	SettingsErrorRollbackFailed      SettingsErrorCode = "rollback_failed"
	SettingsErrorRestartRequired     SettingsErrorCode = "restart_required"
	SettingsErrorTestFailed          SettingsErrorCode = "test_failed"
	SettingsErrorCancelled           SettingsErrorCode = "compositor_cancelled"
	SettingsErrorTransactionBusy     SettingsErrorCode = "transaction_busy"
	SettingsErrorConfirmationExpired SettingsErrorCode = "confirmation_expired"
)

type SettingsApplyOutcomeKind string

const (
	SettingsApplyApplied             SettingsApplyOutcomeKind = "applied"
	SettingsApplyRestartRequired     SettingsApplyOutcomeKind = "restart_required"
	SettingsApplyRolledBack          SettingsApplyOutcomeKind = "rolled_back"
	SettingsApplyPendingConfirmation SettingsApplyOutcomeKind = "pending_confirmation"
	SettingsApplyKept                SettingsApplyOutcomeKind = "kept"
)

type SettingsModuleManifest struct {
	ID              string               `json:"id"`
	Category        SettingsCategory     `json:"category"`
	Title           string               `json:"title"`
	Summary         string               `json:"summary"`
	Icon            string               `json:"icon"`
	Route           string               `json:"route"`
	SearchTerms     []string             `json:"searchTerms"`
	Capabilities    []SettingsCapability `json:"capabilities"`
	BackendAdapter  string               `json:"backendAdapter"`
	UIEntryPoint    string               `json:"uiEntryPoint"`
	ContractVersion uint16               `json:"contractVersion"`
}

type SettingsModuleAvailability struct {
	State  SettingsAvailabilityState `json:"state"`
	Reason string                    `json:"reason,omitempty"`
}

type SettingsCatalogEntry struct {
	Manifest     SettingsModuleManifest     `json:"manifest"`
	Availability SettingsModuleAvailability `json:"availability"`
}

type SettingsCatalogResponse struct {
	SchemaVersion uint16                 `json:"schemaVersion"`
	Modules       []SettingsCatalogEntry `json:"modules"`
}

type SettingsValidationIssue struct {
	Field   string `json:"field"`
	Code    string `json:"code"`
	Message string `json:"message"`
}

type SettingsError struct {
	Code             SettingsErrorCode         `json:"code"`
	Message          string                    `json:"message"`
	Retryable        bool                      `json:"retryable"`
	Issues           []SettingsValidationIssue `json:"issues,omitempty"`
	RestartComponent string                    `json:"restartComponent,omitempty"`
}

type SettingsLoadRequest struct {
	ContractVersion uint16 `json:"contractVersion"`
}

type SettingsResetRequest struct {
	ContractVersion uint16 `json:"contractVersion"`
}

type SettingsDefaultsRequest struct {
	ContractVersion uint16 `json:"contractVersion"`
	BaseRevision    uint64 `json:"baseRevision"`
}

type DiagnosticsSettings struct {
	DiagnosticOverlayEnabled bool `json:"diagnosticOverlayEnabled"`
}

func (settings *DiagnosticsSettings) UnmarshalJSON(data []byte) error {
	var wire struct {
		DiagnosticOverlayEnabled *bool `json:"diagnosticOverlayEnabled"`
	}
	if err := decodeStrict(data, &wire); err != nil {
		return err
	}
	if wire.DiagnosticOverlayEnabled == nil {
		return errors.New("diagnosticOverlayEnabled is required")
	}
	settings.DiagnosticOverlayEnabled = *wire.DiagnosticOverlayEnabled
	return nil
}

type DiagnosticsServiceState struct {
	Enabled      bool   `json:"enabled"`
	Active       bool   `json:"active"`
	EnabledState string `json:"enabledState"`
	ActiveState  string `json:"activeState"`
}

type DiagnosticsComponentHealth struct {
	ID string `json:"id"`; Label string `json:"label"`; State string `json:"state"`; Version string `json:"version"`; Detail string `json:"detail"`; Recovery string `json:"recovery"`
}
type DiagnosticsSupportBundle struct {
	SchemaVersion uint16 `json:"schemaVersion"`; GeneratedAtUnixMillis uint64 `json:"generatedAtUnixMillis"`; ProductVersion string `json:"productVersion"`; SettingsSchemaVersion uint16 `json:"settingsSchemaVersion"`; Components []DiagnosticsComponentHealth `json:"components"`
}

type DiagnosticsSettingsState struct {
	ModuleID        string                     `json:"moduleId"`
	ContractVersion uint16                     `json:"contractVersion"`
	Revision        uint64                     `json:"revision"`
	Active          DiagnosticsSettings        `json:"active"`
	Defaults        DiagnosticsSettings        `json:"defaults"`
	Service         DiagnosticsServiceState    `json:"service"`
	ProductVersion string `json:"productVersion"`
	SettingsSchemaVersion uint16 `json:"settingsSchemaVersion"`
	Components []DiagnosticsComponentHealth `json:"components"`
	SupportBundle DiagnosticsSupportBundle `json:"supportBundle"`
	Availability    SettingsModuleAvailability `json:"availability"`
}

type DiagnosticsValidateRequest struct {
	ContractVersion uint16              `json:"contractVersion"`
	BaseRevision    uint64              `json:"baseRevision"`
	Draft           DiagnosticsSettings `json:"draft"`
}

type SettingsValidationResponse struct {
	Valid  bool                      `json:"valid"`
	Issues []SettingsValidationIssue `json:"issues"`
}

type DiagnosticsApplyRequest struct {
	ContractVersion uint16              `json:"contractVersion"`
	BaseRevision    uint64              `json:"baseRevision"`
	Draft           DiagnosticsSettings `json:"draft"`
}

func (request *DiagnosticsApplyRequest) UnmarshalJSON(data []byte) error {
	var wire struct {
		ContractVersion *uint16              `json:"contractVersion"`
		BaseRevision    *uint64              `json:"baseRevision"`
		Draft           *DiagnosticsSettings `json:"draft"`
	}
	if err := decodeStrict(data, &wire); err != nil {
		return err
	}
	if wire.ContractVersion == nil || wire.BaseRevision == nil || wire.Draft == nil {
		return errors.New("contractVersion, baseRevision, and draft are required")
	}
	request.ContractVersion = *wire.ContractVersion
	request.BaseRevision = *wire.BaseRevision
	request.Draft = *wire.Draft
	return nil
}

type SettingsApplyOutcome struct {
	Kind             SettingsApplyOutcomeKind `json:"kind"`
	RestartComponent string                   `json:"restartComponent,omitempty"`
}

type DiagnosticsApplyResponse struct {
	State   DiagnosticsSettingsState `json:"state"`
	Outcome SettingsApplyOutcome     `json:"outcome"`
}

type DisplayTransform string

const (
	DisplayTransformNormal     DisplayTransform = "normal"
	DisplayTransformRotate90   DisplayTransform = "rotate_90"
	DisplayTransformRotate180  DisplayTransform = "rotate_180"
	DisplayTransformRotate270  DisplayTransform = "rotate_270"
	DisplayTransformFlipped    DisplayTransform = "flipped"
	DisplayTransformFlipped90  DisplayTransform = "flipped_90"
	DisplayTransformFlipped180 DisplayTransform = "flipped_180"
	DisplayTransformFlipped270 DisplayTransform = "flipped_270"
)

type DisplayLeaseState string

const (
	DisplayLeasePending        DisplayLeaseState = "pending"
	DisplayLeaseKept           DisplayLeaseState = "kept"
	DisplayLeaseReverted       DisplayLeaseState = "reverted"
	DisplayLeaseTimedOut       DisplayLeaseState = "timed_out"
	DisplayLeaseRollbackFailed DisplayLeaseState = "rollback_failed"
)

type DisplayReconciliationState string

const (
	DisplayReconciliationNotNeeded        DisplayReconciliationState = "not_needed"
	DisplayReconciliationApplied          DisplayReconciliationState = "applied"
	DisplayReconciliationPartiallyMatched DisplayReconciliationState = "partially_matched"
	DisplayReconciliationSafeFallback     DisplayReconciliationState = "safe_fallback"
	DisplayReconciliationFailed           DisplayReconciliationState = "failed"
)

type DisplayProtocolCapabilities struct {
	OutputManagement   bool   `json:"outputManagement"`
	ProtocolVersion    uint32 `json:"protocolVersion"`
	TestConfiguration  bool   `json:"testConfiguration"`
	ApplyConfiguration bool   `json:"applyConfiguration"`
	AdaptiveSync       bool   `json:"adaptiveSync"`
}

type DisplayMode struct {
	ID             string `json:"id"`
	Width          int32  `json:"width"`
	Height         int32  `json:"height"`
	RefreshMillihz int32  `json:"refreshMillihz"`
	Preferred      bool   `json:"preferred"`
}

type DisplayHeadIdentity struct {
	Name             string `json:"name"`
	Description      string `json:"description"`
	Make             string `json:"make"`
	Model            string `json:"model"`
	SerialNumber     string `json:"serialNumber"`
	PhysicalWidthMM  int32  `json:"physicalWidthMm"`
	PhysicalHeightMM int32  `json:"physicalHeightMm"`
}

type DisplayHeadConfiguration struct {
	ID            string              `json:"id"`
	Identity      DisplayHeadIdentity `json:"identity"`
	Connected     bool                `json:"connected"`
	Enabled       bool                `json:"enabled"`
	Modes         []DisplayMode       `json:"modes"`
	CurrentModeID string              `json:"currentModeId,omitempty"`
	X             int32               `json:"x"`
	Y             int32               `json:"y"`
	ScaleMilli    uint32              `json:"scaleMilli"`
	Transform     DisplayTransform    `json:"transform"`
	AdaptiveSync  bool                `json:"adaptiveSync"`
}

type DisplayTopology struct {
	Serial uint32                     `json:"serial"`
	Heads  []DisplayHeadConfiguration `json:"heads"`
}

type DisplayConfirmationLease struct {
	TransactionID      string            `json:"transactionId"`
	State              DisplayLeaseState `json:"state"`
	DeadlineUnixMillis uint64            `json:"deadlineUnixMillis"`
	RemainingMillis    uint64            `json:"remainingMillis"`
}

type DisplayReconciliationStatus struct {
	State                 DisplayReconciliationState `json:"state"`
	Detail                string                     `json:"detail"`
	MatchedHeads          []string                   `json:"matchedHeads"`
	UnmatchedProfileHeads []string                   `json:"unmatchedProfileHeads"`
}

type DisplaySettingsState struct {
	ModuleID        string                      `json:"moduleId"`
	ContractVersion uint16                      `json:"contractVersion"`
	Revision        uint64                      `json:"revision"`
	Active          DisplayTopology             `json:"active"`
	Defaults        DisplayTopology             `json:"defaults"`
	Capabilities    DisplayProtocolCapabilities `json:"capabilities"`
	Lease           *DisplayConfirmationLease   `json:"lease,omitempty"`
	Reconciliation  DisplayReconciliationStatus `json:"reconciliation"`
	Availability    SettingsModuleAvailability  `json:"availability"`
}

type DisplayValidateRequest struct {
	ContractVersion uint16          `json:"contractVersion"`
	BaseRevision    uint64          `json:"baseRevision"`
	Draft           DisplayTopology `json:"draft"`
}

type DisplayApplyRequest struct {
	ContractVersion           uint16          `json:"contractVersion"`
	BaseRevision              uint64          `json:"baseRevision"`
	Draft                     DisplayTopology `json:"draft"`
	ConfirmationTimeoutMillis uint64          `json:"confirmationTimeoutMillis"`
}

type DisplayApplyResponse struct {
	State   DisplaySettingsState `json:"state"`
	Outcome SettingsApplyOutcome `json:"outcome"`
}

type DisplayLeaseActionRequest struct {
	ContractVersion uint16 `json:"contractVersion"`
	TransactionID   string `json:"transactionId"`
}

type WindowLayoutMode string

const (
	WindowLayoutModeFreeform WindowLayoutMode = "freeform"
	WindowLayoutModeZones    WindowLayoutMode = "zones"
	WindowLayoutModeColumns  WindowLayoutMode = "columns"
)

type WindowLayoutRule string

const (
	WindowLayoutRuleZones       WindowLayoutRule = "zones"
	WindowLayoutRuleMasterStack WindowLayoutRule = "master_stack"
	WindowLayoutRuleDwindle     WindowLayoutRule = "dwindle"
)

type WindowManagementGaps struct {
	OuterHorizontal uint16 `json:"outerHorizontal"`
	OuterVertical   uint16 `json:"outerVertical"`
	InnerHorizontal uint16 `json:"innerHorizontal"`
	InnerVertical   uint16 `json:"innerVertical"`
}

type WindowManagementSettings struct {
	Mode        WindowLayoutMode     `json:"mode"`
	Rule        WindowLayoutRule     `json:"rule"`
	Gaps        WindowManagementGaps `json:"gaps"`
	MasterCount uint8                `json:"masterCount"`
	MasterRatio float64              `json:"masterRatio"`
	SmartGaps   bool                 `json:"smartGaps"`
}

type WindowWorkspaceSummary struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	OutputID     string `json:"outputId"`
	Active       bool   `json:"active"`
	SurfaceCount uint32 `json:"surfaceCount"`
}

type WindowManagementSettingsState struct {
	ModuleID        string                     `json:"moduleId"`
	ContractVersion uint16                     `json:"contractVersion"`
	Revision        uint64                     `json:"revision"`
	Active          WindowManagementSettings   `json:"active"`
	Defaults        WindowManagementSettings   `json:"defaults"`
	Workspaces      []WindowWorkspaceSummary   `json:"workspaces"`
	Availability    SettingsModuleAvailability `json:"availability"`
}

type WindowManagementValidateRequest struct {
	ContractVersion uint16                   `json:"contractVersion"`
	BaseRevision    uint64                   `json:"baseRevision"`
	Draft           WindowManagementSettings `json:"draft"`
}

type WindowManagementApplyRequest = WindowManagementValidateRequest

type WindowManagementApplyResponse struct {
	State   WindowManagementSettingsState `json:"state"`
	Outcome SettingsApplyOutcome          `json:"outcome"`
}

type AppearanceThemeSummary struct {
	ID     string            `json:"id"`
	Name   string            `json:"name"`
	Tokens map[string]string `json:"tokens"`
}

type AppearanceSettings struct {
	ThemeID string `json:"themeId"`
}

type AppearanceSettingsState struct {
	ModuleID        string                     `json:"moduleId"`
	ContractVersion uint16                     `json:"contractVersion"`
	Revision        uint64                     `json:"revision"`
	Active          AppearanceSettings         `json:"active"`
	Defaults        AppearanceSettings         `json:"defaults"`
	Themes          []AppearanceThemeSummary   `json:"themes"`
	RestartRequired bool                       `json:"restartRequired"`
	Availability    SettingsModuleAvailability `json:"availability"`
}

type AppearanceValidateRequest struct {
	ContractVersion uint16             `json:"contractVersion"`
	BaseRevision    uint64             `json:"baseRevision"`
	Draft           AppearanceSettings `json:"draft"`
}

type AppearanceApplyRequest = AppearanceValidateRequest

type AppearanceApplyResponse struct {
	State   AppearanceSettingsState `json:"state"`
	Outcome SettingsApplyOutcome    `json:"outcome"`
}

type ShortcutDefinition struct { ID string `json:"id"`; Title string `json:"title"`; Group string `json:"group"`; Reserved bool `json:"reserved"` }
type ShortcutAssignment struct { ID string `json:"id"`; Accelerator string `json:"accelerator"` }
type ShortcutKeymap struct { Assignments []ShortcutAssignment `json:"assignments"` }
type ShortcutSettingsState struct {
	ModuleID string `json:"moduleId"`; ContractVersion uint16 `json:"contractVersion"`; Revision uint64 `json:"revision"`
	Active ShortcutKeymap `json:"active"`; Defaults ShortcutKeymap `json:"defaults"`; Definitions []ShortcutDefinition `json:"definitions"`; Availability SettingsModuleAvailability `json:"availability"`
}
type ShortcutValidateRequest struct { ContractVersion uint16 `json:"contractVersion"`; BaseRevision uint64 `json:"baseRevision"`; Draft ShortcutKeymap `json:"draft"` }
type ShortcutApplyRequest = ShortcutValidateRequest
type ShortcutApplyResponse struct { State ShortcutSettingsState `json:"state"`; Outcome SettingsApplyOutcome `json:"outcome"` }

func decodeStrict(data []byte, target any) error {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	return decoder.Decode(target)
}
