[package]
name = "protocol-dump"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
protocol-compositor = { path = "../../protocol/protocol-compositor" }
protocol-evidence = { path = "../../protocol/protocol-evidence" }
protocol-os-boundary = { path = "../../protocol/protocol-os-boundary" }
protocol-shell = { path = "../../protocol/protocol-shell" }

[lib]
path = "src/lib.rs"

[lints]
workspace = true

