use protocol_evidence::{CaptureClassification, VisualStatus};

const GENERATED_HEADER: &str = "\
// @generated by protocol-codegen. Do not edit by hand.
// Source of truth: de-rs/crates/protocol/*.

";

pub fn generated_contract_banner() -> &'static str {
    "agora-de protocol contracts"
}

pub fn generate_typescript_contracts() -> String {
    let visual_status_union = typescript_string_union(
        "VisualStatus",
        VisualStatus::ALL
            .iter()
            .map(VisualStatus::wire_name)
            .collect::<Vec<_>>()
            .as_slice(),
    );
    let capture_classification_union = typescript_string_union(
        "CaptureClassification",
        CaptureClassification::ALL
            .iter()
            .map(CaptureClassification::wire_name)
            .collect::<Vec<_>>()
            .as_slice(),
    );

    let body = [
        "export type SurfaceEventKind = 'mapped' | 'unmapped' | 'focused' | 'input_denied';",
        "",
        "export interface SurfaceEvent {",
        "  readonly surfaceId: string;",
        "  readonly kind: SurfaceEventKind;",
        "  readonly ownerUid: number;",
        "}",
        "",
        "export interface ThemeToken {",
        "  readonly name: string;",
        "  readonly value: string;",
        "}",
        "",
        "export interface AdminEscalationSummary {",
        "  readonly id: string;",
        "  readonly requestedAtUnixMillis: number;",
        "  readonly actorUid: number;",
        "}",
        "",
        visual_status_union.as_str(),
        "",
        capture_classification_union.as_str(),
        "",
        "export interface EvidencePacket {",
        "  readonly scenario: string;",
        "  readonly capturedAtUnixMillis: number;",
        "  readonly visualStatus: VisualStatus;",
        "  readonly captureClassification: CaptureClassification;",
        "}",
        "",
    ]
    .join("\n");

    format!("{GENERATED_HEADER}{body}")
}

fn typescript_string_union(name: &str, variants: &[&str]) -> String {
    let mut lines = Vec::with_capacity(variants.len() + 1);
    lines.push(format!("export type {name} ="));
    for (index, variant) in variants.iter().enumerate() {
        let suffix = if index + 1 == variants.len() { ";" } else { "" };
        lines.push(format!("  | '{variant}'{suffix}"));
    }
    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::generate_typescript_contracts;

    #[test]
    fn generated_contracts_are_stable() {
        let generated = generate_typescript_contracts();
        assert!(generated.contains("export interface SurfaceEvent"));
        assert!(generated.contains("| 'capture_visible'"));
        assert!(generated.ends_with('\n'));
    }
}
