const GENERATED_HEADER: &str = "\
// @generated by protocol-codegen. Do not edit by hand.
// Source of truth: de-rs/crates/protocol/*.

";

pub fn generated_contract_banner() -> &'static str {
    "agora-de protocol contracts"
}

pub fn generate_typescript_contracts() -> String {
    let body = [
        "export type SurfaceEventKind = 'mapped' | 'unmapped' | 'focused' | 'input_denied';",
        "",
        "export interface SurfaceEvent {",
        "  readonly surfaceId: string;",
        "  readonly kind: SurfaceEventKind;",
        "  readonly ownerUid: number;",
        "}",
        "",
        "export interface ThemeToken {",
        "  readonly name: string;",
        "  readonly value: string;",
        "}",
        "",
        "export interface AdminEscalationSummary {",
        "  readonly id: string;",
        "  readonly requestedAtUnixMillis: number;",
        "  readonly actorUid: number;",
        "}",
        "",
        "export type VisualStatus = 'visible' | 'blank' | 'unknown';",
        "",
        "export type CaptureClassification =",
        "  | 'insufficient_mapped_only'",
        "  | 'frame_presented'",
        "  | 'capture_visible'",
        "  | 'blank_capture_failure'",
        "  | 'not_visible';",
        "",
        "export interface EvidencePacket {",
        "  readonly scenario: string;",
        "  readonly capturedAtUnixMillis: number;",
        "  readonly visualStatus: VisualStatus;",
        "  readonly captureClassification: CaptureClassification;",
        "}",
        "",
    ]
    .join("\n");

    format!("{GENERATED_HEADER}{body}")
}

#[cfg(test)]
mod tests {
    use super::generate_typescript_contracts;

    #[test]
    fn generated_contracts_are_stable() {
        let generated = generate_typescript_contracts();
        assert!(generated.contains("export interface SurfaceEvent"));
        assert!(generated.ends_with('\n'));
    }
}
