use protocol_compositor::{
    LayoutActionKind, LayoutMode, SurfaceEventKind, SurfaceLayoutParticipation, SurfacePolicyClass,
};
use protocol_evidence::{CaptureClassification, VisualStatus};
use protocol_os_boundary::AgentState;

const GENERATED_HEADER: &str = "\
// @generated by protocol-codegen. Do not edit by hand.
// Source of truth: de-rs/crates/protocol/*.

";

pub fn generated_contract_banner() -> &'static str {
    "agora-de protocol contracts"
}

pub fn generate_typescript_contracts() -> String {
    let surface_event_kind_union = typescript_string_union(
        "SurfaceEventKind",
        SurfaceEventKind::ALL
            .iter()
            .map(SurfaceEventKind::wire_name)
            .collect::<Vec<_>>()
            .as_slice(),
    );
    let layout_mode_union = typescript_string_union(
        "LayoutMode",
        LayoutMode::ALL
            .iter()
            .map(LayoutMode::wire_name)
            .collect::<Vec<_>>()
            .as_slice(),
    );
    let surface_layout_participation_union = typescript_string_union(
        "SurfaceLayoutParticipation",
        SurfaceLayoutParticipation::ALL
            .iter()
            .map(SurfaceLayoutParticipation::wire_name)
            .collect::<Vec<_>>()
            .as_slice(),
    );
    let surface_policy_class_union = typescript_string_union(
        "SurfacePolicyClass",
        SurfacePolicyClass::ALL
            .iter()
            .map(SurfacePolicyClass::wire_name)
            .collect::<Vec<_>>()
            .as_slice(),
    );
    let layout_action_kind_union = typescript_string_union(
        "LayoutActionKind",
        LayoutActionKind::ALL
            .iter()
            .map(LayoutActionKind::wire_name)
            .collect::<Vec<_>>()
            .as_slice(),
    );
    let visual_status_union = typescript_string_union(
        "VisualStatus",
        VisualStatus::ALL
            .iter()
            .map(VisualStatus::wire_name)
            .collect::<Vec<_>>()
            .as_slice(),
    );
    let capture_classification_union = typescript_string_union(
        "CaptureClassification",
        CaptureClassification::ALL
            .iter()
            .map(CaptureClassification::wire_name)
            .collect::<Vec<_>>()
            .as_slice(),
    );
    let agent_state_union = typescript_string_union(
        "AgentState",
        AgentState::ALL
            .iter()
            .map(|state| state.wire_name())
            .collect::<Vec<_>>()
            .as_slice(),
    );

    let body = [
        surface_event_kind_union.as_str(),
        "",
        "export interface SurfaceEvent {",
        "  readonly surfaceId: string;",
        "  readonly kind: SurfaceEventKind;",
        "  readonly ownerUid: number;",
        "}",
        "",
        layout_mode_union.as_str(),
        "",
        surface_layout_participation_union.as_str(),
        "",
        surface_policy_class_union.as_str(),
        "",
        layout_action_kind_union.as_str(),
        "",
        "export interface SurfaceGeometry {",
        "  readonly x: number;",
        "  readonly y: number;",
        "  readonly width: number;",
        "  readonly height: number;",
        "}",
        "",
        "export interface LayoutSurface {",
        "  readonly surfaceId: string;",
        "  readonly label: string;",
        "  readonly appId: string;",
        "  readonly title: string;",
        "  readonly role: string;",
        "  readonly outputId: string;",
        "  readonly parentSurfaceId: string;",
        "  readonly workspaceId: string;",
        "  readonly zoneId: string;",
        "  readonly mode: LayoutMode;",
        "  readonly participation: SurfaceLayoutParticipation;",
        "  readonly policyClass: SurfacePolicyClass;",
        "  readonly policyReason: string;",
        "  readonly floating: boolean;",
        "  readonly focused: boolean;",
        "  readonly visible: boolean;",
        "  readonly geometry?: SurfaceGeometry;",
        "  readonly order: number;",
        "}",
        "",
        "export interface LayoutZone {",
        "  readonly id: string;",
        "  readonly name: string;",
        "  readonly kind: string;",
        "  readonly surfaceIds: readonly string[];",
        "}",
        "",
        "export interface LayoutWorkspace {",
        "  readonly id: string;",
        "  readonly name: string;",
        "  readonly outputId: string;",
        "  readonly active: boolean;",
        "  readonly zones: readonly LayoutZone[];",
        "  readonly surfaceOrder: readonly string[];",
        "}",
        "",
        "export interface LayoutState {",
        "  readonly mode: LayoutMode;",
        "  readonly revision: number;",
        "  readonly surfaces: readonly LayoutSurface[];",
        "  readonly workspaces: readonly LayoutWorkspace[];",
        "}",
        "",
        "export interface ThemeToken {",
        "  readonly name: string;",
        "  readonly value: string;",
        "}",
        "",
        "export interface CatalogApp {",
        "  readonly id: string;",
        "  readonly name: string;",
        "  readonly icon: string;",
        "}",
        "",
        "export interface CatalogAppsResponse {",
        "  readonly apps: readonly CatalogApp[];",
        "}",
        "",
        "export interface AdminEscalationSummary {",
        "  readonly id: string;",
        "  readonly requestedAtUnixMillis: number;",
        "  readonly actorUid: number;",
        "  readonly summary: string;",
        "}",
        "",
        agent_state_union.as_str(),
        "",
        "export interface AgentInfo {",
        "  readonly uid: number;",
        "  readonly displayName: string;",
        "  readonly state: AgentState;",
        "}",
        "",
        "export interface AuditEvent {",
        "  readonly id: string;",
        "  readonly actorUid: number;",
        "  readonly action: string;",
        "  readonly subject: string;",
        "  readonly createdAtUnixMillis: number;",
        "}",
        "",
        visual_status_union.as_str(),
        "",
        capture_classification_union.as_str(),
        "",
        "export interface EvidencePacket {",
        "  readonly scenario: string;",
        "  readonly capturedAtUnixMillis: number;",
        "  readonly visualStatus: VisualStatus;",
        "  readonly captureClassification: CaptureClassification;",
        "}",
        "",
    ]
    .join("\n");

    format!("{GENERATED_HEADER}{body}")
}

fn typescript_string_union(name: &str, variants: &[&str]) -> String {
    let mut lines = Vec::with_capacity(variants.len() + 1);
    lines.push(format!("export type {name} ="));
    for (index, variant) in variants.iter().enumerate() {
        let suffix = if index + 1 == variants.len() { ";" } else { "" };
        lines.push(format!("  | '{variant}'{suffix}"));
    }
    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::generate_typescript_contracts;

    #[test]
    fn generated_contracts_are_stable() {
        let generated = generate_typescript_contracts();
        assert!(generated.contains("export interface SurfaceEvent"));
        assert!(generated.contains("export type LayoutActionKind"));
        assert!(generated.contains("export type SurfacePolicyClass"));
        assert!(generated.contains("readonly policyClass: SurfacePolicyClass"));
        assert!(generated.contains("export interface LayoutState"));
        assert!(generated.contains("export interface CatalogAppsResponse"));
        assert!(generated.contains("export type AgentState"));
        assert!(generated.contains("| 'capture_visible'"));
        assert!(generated.ends_with('\n'));
    }
}
