[package]
name = "protocol-evidence"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
de-error = { path = "../../foundation/de-error" }
de-ids = { path = "../../foundation/de-ids" }
de-time = { path = "../../foundation/de-time" }

[lib]
path = "src/lib.rs"

[lints]
workspace = true

